# Generated by Django 4.2.4 on 2023-08-30 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('createdOn', models.TimeField(default=datetime.datetime.now)),
                ('updatedOn', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
