# Generated by Django 4.2.4 on 2023-08-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_box_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='createdBy',
        ),
    ]
