# Generated by Django 4.2.4 on 2023-08-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_box_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='area',
        ),
        migrations.RemoveField(
            model_name='box',
            name='volume',
        ),
    ]
