# Generated by Django 4.2.4 on 2023-08-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_box_area_remove_box_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
