# Generated by Django 4.2.4 on 2023-08-31 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_box_createdon_alter_box_updatedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
